version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
    #had to tweek this, because windows user have a different command to the video guy
      - /home/node/app/node_modules 
      - /home/kayabornschein/frontend:/home/node/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules 
      - /home/kayabornschein/frontend:/home/node/app
    command: ["npm", "run", "test"]